<?xml  version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN"   "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0" >
<!-- Generated via Iro -->
<dict>
  <key>fileTypes</key>
  <array>
    <string>tr</string>
   </array>
  <key>name</key>
  <string>troll</string>
  <key>patterns</key>
  <array>
    <dict>
      <key>include</key>
      <string>#main</string>
    </dict>
   </array>
  <key>scopeName</key>
  <string>source.troll</string>
  <key>uuid</key>
  <string></string>
  <key>repository</key>
  <dict>
    <key>main</key>
    <dict>
      <key>patterns</key>
      <array>
        <dict>
          <key>match</key>
          <string>(function|call|compositional)</string>
          <key>name</key>
          <string>keyword.other.troll</string>
        </dict>
        <dict>
          <key>match</key>
          <string>(if|then|else|foreach|while|do|until|in)</string>
          <key>name</key>
          <string>keyword.control.troll</string>
        </dict>
        <dict>
          <key>match</key>
          <string>(\=|\*|\+|\-|:=|&lt;|&gt;|&lt;=|&gt;=)</string>
          <key>name</key>
          <string>keyword.operator.troll</string>
        </dict>
        <dict>
          <key>match</key>
          <string>(\d?[d\x{007c}D]?\d+)</string>
          <key>name</key>
          <string>constant.numeric.troll</string>
        </dict>
        <dict>
          <key>match</key>
          <string>(\b[a-z][a-z0-9]*)</string>
          <key>name</key>
          <string>variable.other.troll</string>
        </dict>
        <dict>
          <key>match</key>
          <string>(\(|\)|,)</string>
          <key>name</key>
          <string>punctuation.troll</string>
        </dict>
        <dict>
          <key>begin</key>
          <string>(&quot;)</string>
          <key>beginCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>punctuation.troll</string>
            </dict>
          </dict>
          <key>contentName</key>
          <string>string.quoted.troll</string>
          <key>end</key>
          <string>(&quot;)</string>
          <key>endCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>punctuation.troll</string>
            </dict>
          </dict>
        </dict>
        <dict>
          <key>match</key>
          <string>(\\.*)</string>
          <key>name</key>
          <string>comment.line.troll</string>
        </dict>
        <dict>
          <key>match</key>
          <string>([^\s])</string>
          <key>name</key>
          <string>invalid.illegal.troll</string>
        </dict>
       </array>
    </dict>
    <key>main__1</key>
    <dict>
      <key>patterns</key>
      <array>
       </array>
    </dict>
  </dict>
</dict>
</plist>
